### ISSUE TITLE
Changing minutes with the keyboard has no effect

### ISSUE THREAD

**Issue by snokleby** [VitaliiBlagodir/cordova-plugin-datepicker#106] opened 2015-07-17 05:42 UTC
I use the plugin with mode 'time'. If the users want to change from the default, e.g. 06:00, to 06:30, they have to tap 30 times. After tapping a few times, I notice they instead type 30 into the minutes field. This ends up having no effect, the time is not changed to what is displayed in the plugin.

This would not have been that critical, if I could set the minute-interval to e.g. 5 for Android.

**Comment by ecthurlow** [comment] 2015-07-17 11:03
I've made a pull request you can use as a fix for this (#100). The problem is that in Android, the timepicker only stores typed values once the field loses focus, which I've set it to do once the user click's the positive button.

**Comment by snokleby** [comment] 2015-07-17 11:41
Thank you. I will check it out, and hopefully it will get merged into the main repository soon.

**Comment by VitaliiBlagodir** [comment] 2015-07-17 12:17
Good job @ecthurlow! Merged https://github.com/VitaliiBlagodir/cordova-plugin-datepicker/pull/100

**Closed by VitaliiBlagodir** 2015-07-17 12:17 UTC
Labels: bug
