### ISSUE TITLE
NullPointerException on Call (test on 5.0 (HTC One) and 5.1 (Emulator))

### ISSUE THREAD

**Issue by AngryAxel** [VitaliiBlagodir/cordova-plugin-datepicker#95] opened 2015-06-20 11:02 UTC
I already commented this into the line, i have no idea how to fix this, with the old version it was working

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference
            at com.plugin.datepicker.DatePickerPlugin.prepareDialog(DatePickerPlugin.java:160)
            at com.plugin.datepicker.DatePickerPlugin.access$1300(DatePickerPlugin.java:37)
            at com.plugin.datepicker.DatePickerPlugin$2.run(DatePickerPlugin.java:128)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:155)
            at android.app.ActivityThread.main(ActivityThread.java:5696)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1028)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)

**Comment by AngryAxel** [comment] 2015-06-20 11:27
Here is what i call:
$scope.showDatePicker = function() {
        today = new Date();
        var options = {
            date: today,
            mode: 'date',
            minDate: today
        };
};

**Comment by andrelsmoraes** [comment] 2015-06-20 11:29
I will validate these null values, check for update soon.

**Comment by AngryAxel** [comment] 2015-06-20 11:30
thanks for the fast reply, if you need more informations just ask for it ;)

**Comment by andrelsmoraes** [comment] 2015-06-20 11:37
Thank you for reporting. I can't correct it right now, but I'll do it as
soon as I get home (8 - 12 hours from now).

If you are in urgency, try to set okText, cancelText, todayText and nowText
to empty string, ex:

$scope.showDatePicker = function() { today = new Date(); var options = {
date: today, mode: 'date', minDate: today, okText: '', cancelText: '',
nowText: '', todayText: '' }; datePicker.show(options, function(date){
if(date != undefined){ $scope.debt.deadline = date; $scope.$apply(); } });
};

Best regards,

Em sáb, 20 de jun de 2015 08:30, AngryAxel <notifications@github.com>
escreveu:

**Comment by andrelsmoraes** [comment] 2015-06-20 11:41
I can't correct it right now, but I'll do it as soon as I get home (8 - 12 hours from now).

If you are in urgency, try to set okText, cancelText, todayText and nowText to empty string at your options var.

**Comment by AngryAxel** [comment] 2015-06-20 12:06
well that doesn't work for me :/ still the same issue in line 160 & 167 but i removed the check for now, 
String labelCancel = currentCtx.getString(android.R.string.cancel);
String labelOk = currentCtx.getString(android.R.string.ok);

Now i can continue working on my App :P

**Comment by andrelsmoraes** [comment] 2015-06-20 12:13
I'm sorry for that, I'll work on this soon. Thank you again!

**Comment by andrelsmoraes** [comment] 2015-06-21 04:43
I couldn't reproduce your error, even if I pass null to okText, it assigns "null" to the label of the button.

I created a method isNotEmpty to assure that the values (in options) won't be null.

But, I found that on emulator (Android 5.1), the onDateSet and OnTimeSet event were not being fired. It worked fine on Galaxy S3 4.2.2.

So I forced onDateSet and onTimeSet to be called when POSITIVE or NEUTRAL buttons are pressed.

These changes need more tests, so it's not provided yet... I'll ask you to wait a little more.

**Comment by AngryAxel** [comment] 2015-06-21 10:29
okay we are talking about #94 :P i can confirm that aswell

**Comment by andrelsmoraes** [comment] 2015-06-21 14:14
Yes, I need to get used to the "issues" system, I didn't noticed the #94 until you mentioned.

**Comment by AngryAxel** [comment] 2015-06-21 14:17
I really like the issue system :) We use it in our project for like everything

**Comment by andrelsmoraes** [comment] 2015-06-21 16:38
Fixed on #96.

Sorry for the mess, if you find anything else, please report. Thanks.

**Closed** 2015-06-26 09:43 UTC
